services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: EryndorRecordsTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fakePassword
